# Generated by Django 5.2.17 on 2026-09-25 07:08

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название урока')),
                ('topic', models.TextField(blank=True, verbose_name='Тема / описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('open_for', models.ManyToManyField(blank=True, related_name='open_lessons', to='core.studygroup', verbose_name='Открыт для групп')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='ФИО')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.studygroup', verbose_name='Группа')),
            ],
            options={
                'ordering': ['full_name', 'username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('statement', models.TextField(blank=True, help_text='Поддерживается Markdown: **жирный**, `код`, списки, блоки кода.', verbose_name='Условие')),
                ('input_format', models.TextField(blank=True, verbose_name='Формат ввода')),
                ('output_format', models.TextField(blank=True, verbose_name='Формат вывода')),
                ('kind', models.CharField(choices=[('io', 'Автопроверка на тестах'), ('manual', 'Вручную, преподавателем')], default='io', max_length=10, verbose_name='Тип проверки')),
                ('time_limit', models.FloatField(default=2, verbose_name='Лимит времени, с')),
                ('memory_limit', models.PositiveIntegerField(default=256, verbose_name='Лимит памяти, МБ')),
                ('starter_code', models.TextField(blank=True, verbose_name='Начальный код')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_open', models.BooleanField(default=True, verbose_name='Задача открыта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.lesson', verbose_name='Урок')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('running', 'Проверяется'), ('OK', 'Верно'), ('WA', 'Неверный ответ'), ('TLE', 'Превышено время'), ('MLE', 'Превышена память'), ('RE', 'Ошибка выполнения'), ('CE', 'Синтаксическая ошибка'), ('OLE', 'Слишком большой вывод'), ('SE', 'Ошибка проверяющей системы'), ('review', 'Ждёт проверки'), ('accepted', 'Зачтено'), ('rejected', 'Не зачтено')], default='pending', max_length=10)),
                ('tests_total', models.PositiveIntegerField(default=0)),
                ('tests_passed', models.PositiveIntegerField(default=0)),
                ('failed_test', models.PositiveIntegerField(blank=True, null=True)),
                ('failed_is_sample', models.BooleanField(default=False)),
                ('max_time', models.FloatField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('failed_input', models.TextField(blank=True)),
                ('failed_expected', models.TextField(blank=True)),
                ('failed_output', models.TextField(blank=True)),
                ('teacher_comment', models.TextField(blank=True, verbose_name='Комментарий преподавателя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(blank=True, verbose_name='Входные данные')),
                ('output_data', models.TextField(blank=True, verbose_name='Ожидаемый вывод')),
                ('is_sample', models.BooleanField(default=False, verbose_name='Пример')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='core.task')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
