# Generated by Django 5.2.17 on 2026-09-25 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_login',
            field=models.BooleanField(default=False, verbose_name='Вход по ID'),
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.CharField(choices=[('login', 'Вход'), ('login_fail', 'Неудачный вход'), ('run', 'Запуск'), ('submit', 'Отправка')], max_length=12)),
                ('details', models.CharField(blank=True, max_length=200)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ip', 'created_at'], name='core_access_ip_4f9b4f_idx'), models.Index(fields=['user', 'created_at'], name='core_access_user_id_dcfe67_idx')],
            },
        ),
    ]
