# Generated by Django 5.2.17 on 2026-09-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_access_log_id_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_session', models.BooleanField(default=True, help_text='При входе под ID на другом компьютере прежний компьютер выходит из аккаунта.', verbose_name='Один вход на аккаунт студента')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки сайта',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='session_key',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='action',
            field=models.CharField(choices=[('login', 'Вход'), ('login_fail', 'Неудачный вход'), ('kicked', 'Вытеснен другим входом'), ('run', 'Запуск'), ('submit', 'Отправка')], max_length=12),
        ),
    ]
