# Generated by Django 5.2.17 on 2026-09-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_single_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код занятия')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='open_for_sections',
            field=models.ManyToManyField(blank=True, related_name='open_lessons', to='core.classsection', verbose_name='Открыт для занятий'),
        ),
        migrations.AddField(
            model_name='user',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='students', to='core.classsection', verbose_name='Занятия'),
        ),
    ]
