# Generated by Django 5.2.17 on 2026-10-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_class_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='Язык интерфейса'),
        ),
    ]
