# Generated by Django 5.2.17 on 2026-10-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_multilang_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название урока (EN)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_kk',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название урока (KK)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='topic_en',
            field=models.TextField(blank=True, verbose_name='Тема / описание (EN)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='topic_kk',
            field=models.TextField(blank=True, verbose_name='Тема / описание (KK)'),
        ),
        migrations.AddField(
            model_name='task',
            name='input_format_en',
            field=models.TextField(blank=True, verbose_name='Формат ввода (EN)'),
        ),
        migrations.AddField(
            model_name='task',
            name='input_format_kk',
            field=models.TextField(blank=True, verbose_name='Формат ввода (KK)'),
        ),
        migrations.AddField(
            model_name='task',
            name='output_format_en',
            field=models.TextField(blank=True, verbose_name='Формат вывода (EN)'),
        ),
        migrations.AddField(
            model_name='task',
            name='output_format_kk',
            field=models.TextField(blank=True, verbose_name='Формат вывода (KK)'),
        ),
        migrations.AddField(
            model_name='task',
            name='statement_en',
            field=models.TextField(blank=True, help_text='Поддерживается Markdown: **жирный**, `код`, списки, блоки кода.', verbose_name='Условие (EN)'),
        ),
        migrations.AddField(
            model_name='task',
            name='statement_kk',
            field=models.TextField(blank=True, help_text='Поддерживается Markdown: **жирный**, `код`, списки, блоки кода.', verbose_name='Условие (KK)'),
        ),
        migrations.AddField(
            model_name='task',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='task',
            name='title_kk',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название (KK)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название урока (RU)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='topic_ru',
            field=models.TextField(blank=True, verbose_name='Тема / описание (RU)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='input_format_ru',
            field=models.TextField(blank=True, verbose_name='Формат ввода (RU)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='output_format_ru',
            field=models.TextField(blank=True, verbose_name='Формат вывода (RU)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='statement_ru',
            field=models.TextField(blank=True, help_text='Поддерживается Markdown: **жирный**, `код`, списки, блоки кода.', verbose_name='Условие (RU)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название (RU)'),
        ),
    ]
